### ISSUE TITLE
Refactor Test Work Breakdown

### ISSUE THREAD

**Issue by NickCorbett** [awslabs/aws-orbit-workbench#1015]
Create tasks that define how we migrate our existing regression tests from the old method to the new framework.

**Comment by stthoom** [comment]
WIP - Refactor lake-admin regression driver notebook into PyTest and KubeTest based module. 

Identify Fixtures scope, markers and retry capabilities.

**Comment by stthoom** [comment]
#1043 
#1044

**Comment by stthoom** [comment]
#1052 
#1053

**Comment by stthoom** [comment]
Usage of EFS filesystem based file checks in regression driver notebooks can not be carried forward to PyTest based approach. Need to rely on the operator driven CustomResource status value.

**Comment by stthoom** [comment]
Refactored the Regression driver notebooks into PyTest files. Testing the PyTest files will be tracked in a different task.
