### ISSUE TITLE
[FEATURE] - Testing the Regression Pipeline after PyTest Refactor

### ISSUE THREAD

**Issue by NickCorbett** [awslabs/aws-orbit-workbench#1061]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stthoom** [comment]
Bugs found. 
#1077 
#1078

**Comment by stthoom** [comment]
Closing this task. Needs above bug fixes.
