### ISSUE TITLE
deploy_id hex all digit value starting with 0 converts to a float from CF output variables

### ISSUE THREAD

**Issue by stthoom** [awslabs/aws-orbit-workbench#110]
Known pattern - https://github.com/aws/serverless-application-model/issues/200#issuecomment-570701231 

manifest.toolkit_s3_bucket: datamaker-dev-env-toolkit-198245574422-45596.0    [ Error ] NoSuchBucket: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist

**Comment by abaror** [comment]
cannot reproduce
