### ISSUE TITLE
[BUG] - Document the Documentation Updates

### ISSUE THREAD

**Issue by NickCorbett** [awslabs/aws-orbit-workbench#1227]
The documentation is out of date.

This task is complete when we have a list of the documentation pages that need updating

**Comment by NickCorbett** [comment]
The TOUR has its flow defined and can be reworked / added to as needed.  The following pages need to be edited and completed:
Getting Started
	•	Logging In
	•	Notebook Server
	•	Notebook Server Configurations
Jupyter Labs Landing Page
	•	Catalog
	•	Compute
	•	EKS Jobs
	•	Glue Data Brew
	•	Storage
	•	Teams
Jupyter Notebooks
	•	Glue Examples
	•	Sagemaker Examples
	•	Athena Examples
Visual Studio Code
	•	Start Up
	•	AWS Toolkit Extension
	•	SQL Tools

**Comment by dgraeber** [comment]
https://quip-amazon.com/praUA63m2r6W/Untitled#temp:C:FYXe5a9e27c9b12117919778922c
