### ISSUE TITLE
[BUG] - Remove destroy toolkit from env destroy

### ISSUE THREAD

**Issue by dgraeber** [awslabs/aws-orbit-workbench#1250]
the toolkit needs to exist outside of the `orbit destroy env` --

**Comment by srinivasreddych** [comment]
destroy_toolkit should be in there for every destroy action of layers of orbit (foundation, env) because we deploy IAM role and policies as a part of toolkit deployment and they need to be cleaned up automatically as a part of layer deletion IMO.

**Comment by srinivasreddych** [comment]
As discussed offline, `destroy_toolkit` is a needed functionality which needs to happen during orbit layers destroy action. Closing it.

**Comment by dgraeber** [comment]
Re-opening this for discussion.  We have a separate deploy step for orbit (`orbit deploy toolkit`) .  This contains the reference to the codebuild role.  The need for this issue is to confirm that the destruction of the env and teams DOES NOT destroy the toolkit that is created in the `orbit deploy toolkit `step (confirm that this toolkit is intact after the env is destroyed).  If it is destroyed, then we cannot destroy images or credentials for a full cleanup.
