### ISSUE TITLE
[BUG] - Remove Orbit codeartifact from foundation

### ISSUE THREAD

**Issue by dgraeber** [awslabs/aws-orbit-workbench#1254]
With the remote toolkit (codeseeder) we no longer need references to the orbit codeartifact.  

Review the deployment of foundation, env , and teams and remove as necessary references to code artifact for orbit (NOT SLRT):
- cli for forundation
- deployment references in foundation, env, teams

**Comment by stthoom** [comment]
Removed CA creation from orbit CLI. Deployed Foundation, Env and Teams with out Orbit CA instead used Toolkit CA domain and repo. Raising PR.
