### ISSUE TITLE
[BUG] - Orbit deploy toolkit not resolving parameters

### ISSUE THREAD

**Issue by dgraeber** [awslabs/aws-orbit-workbench#1263]
The `orbit deploy toolkit ` does not take into account environment parameters such as AWS_ACCOUNT_ID and AWS_DEFAULT_REGION when writing the Context.  In this case, if images are populated, these env params are not evaluated resulting in an SSM that is incorrect (??). 

To Replicate:
Create a new manifest with Images section filled out (ex below) and run `orbit deploy toolkit `.  Look at the SSM when done.

**Comment by chamcca** [comment]
N/A
