### ISSUE TITLE
Add Spark Support with AWS Glue Interactive Sessions

### ISSUE THREAD

**Issue by OElesin** [awslabs/aws-orbit-workbench#1320]

**Comment by dgraeber** [comment]
@OElesin Thanks for reaching out.  We will review whether to include the kernels in our images.  

You can install the kernels into the Docker image (ref the Glue Developer Endpoint integration image) 
Please see https://docs.aws.amazon.com/glue/latest/dg/interactive-sessions.html

**Comment by OElesin** [comment]
Your recommendation: Glue Developer Endpoint or Glue Interactive Session for Spark Integration with Orbit Workbench?

**Comment by dgraeber** [comment]
The interactive session kernel is what I would suggest trying.
