### ISSUE TITLE
[BUG] - Codebuild Project/Deployer Hangs

### ISSUE THREAD

**Issue by AllOtherUserNamesTaken** [awslabs/aws-orbit-workbench#1330]
**Describe the bug**
CodeBuild project hangs for several hours.

**To Reproduce**
1. Clone [AWS Labs github repository](https://awslabs.github.io/aws-orbit-workbench/detail-clone)
2. Install the [CLI](https://awslabs.github.io/aws-orbit-workbench/detail-cli)
3. Install [AWS CodeSeeder](https://awslabs.github.io/aws-orbit-workbench/detail-codeseeder)
4. Generate a new [manifest](https://awslabs.github.io/aws-orbit-workbench/detail-manifest)
5. Deploy a new [foundation](https://awslabs.github.io/aws-orbit-workbench/detail-foundation) (edit: skipped used existing VPC and subnets)
6. Deploy a new [toolkit](https://awslabs.github.io/aws-orbit-workbench/detail-toolkit)
7. Deploy [credentials](https://awslabs.github.io/aws-orbit-workbench/detail-credentials)
8. Deploy [docker images](https://awslabs.github.io/aws-orbit-workbench/detail-images)
9. Deploy [environment](https://awslabs.github.io/aws-orbit-workbench/detail-environment) (edit: last attempted step)
10. Deploy [teams](https://awslabs.github.io/aws-orbit-workbench/detail-teams) (edit: never executed)

**Expected behavior**
Expect CodeBuild project to fail or succeed.

**Screenshots**
![image](https://user-images.githubusercontent.com/24562333/179514125-816f4094-5149-4f32-89fc-5731d1372006.png)

**Desktop (please complete the following information):**
 - EC2 instance
 - OS: [ubunut 20.04]

**Additional context**
While attempting to deploy, I had to make changes to both codeseeder and the cli to ensure that the S3 buckets for the toolkit were encrypted. I also had to update the orbit cli's remote-requirements.txt to use the latest 1.* release of AWS Python SDK because the current default version of node running in the codebuild project's agent does not support older versions of the SDK.

**Comment by chamcca** [comment]
are you able to get the complete logs from the codebuild execution?

**Comment by chamcca** [comment]
did you actually install the **foundation** or did you use existing vpcs, subnets, etc? I was able to reproduce the cdk hangup and have determined the cause, but the same issue would have affected the **foundation** deployment as well as the **env** deployment.

**Comment by AllOtherUserNamesTaken** [comment]
@chamcca you are correct I had to use existing VPCs and subnets. There aren't additional logs, it just hangs.

**Comment by bozethe** [comment]
@[chamcca]I have the same issue as well but my deployment get stack at foundation stage. It just stack on below stage (/remote_files/cdk/foundation.py ). 



[2022-07-12 16:32:52,007][deploy.py    :337] CDK Toolkit Stack deployed
--
578 | [2022-07-12 16:32:52,007][foundation.py: 34] Deploying self signed cert...
579 | [2022-07-12 16:32:52,007][cert.py      : 35] Generating self-signed certificate...
580 | [2022-07-12 16:32:52,007][cert.py      : 37] Creating private key...
581 | [2022-07-12 16:32:52,158][cert.py      : 41] Creating Certificate signing request...
582 | [2022-07-12 16:32:52,166][cert.py      : 49] Creating Public certificate...
583 | [2022-07-12 16:32:52,172][cert.py      : 59] Uploading the cert to IAM...
584 | [2022-07-12 16:32:52,698][foundation.py: 37] Deploying orbit-f-dev-env Foundation...
585 | [2022-07-12 16:32:52,698][sh.py        : 28] + cdk deploy --require-approval never --progress events --toolkit-stack-name orbit-f-dev-env-cdk-toolkit --app "python /root/.venv/lib/python3.7/site-packages/aws_orbit/remote_files/cdk/foundation.py dev-env arn:aws:iam::903917712828:server-certificate/dev-env-eu-west-1" --output .orbit.out/dev-env/cdk/orbit-f-dev-env

**Comment by AllOtherUserNamesTaken** [comment]
Thank you @chamcca we have also verified that this allowed progress.

**Comment by bozethe** [comment]
Thanks @chamcca. Adding constructs and jsii fixed the problem.
