### ISSUE TITLE
[BUG] -Waiting for for Ingress istio-ingress.istio-system failed

### ISSUE THREAD

**Issue by bozethe** [awslabs/aws-orbit-workbench#1337]
**Describe the bug**
The codebuild fails with "Waiting for for Ingress istio-ingress.istio-system". I was on step 9 of the installation guide when I experienced the problem(orbit deploy env -f manifest.yaml ). I am not sure but I think the elb should be created but I see there is no elb created. 

**To Reproduce**
[Steps to reproduce the behavior:
3. Scroll down to '....'](https://awslabs.github.io/aws-orbit-workbench/deploy-steps
1. Clone AWS Labs github repository
2. Install the CLI
3. Install AWS CodeSeeder
4. Generate a new manifest
5. Deploy a new foundation
6. Deploy a new toolkit
7. Deploy credentials
8. Deploy docker images
9. Deploy environment)
![image](https://user-images.githubusercontent.com/15804600/181070127-5200dff5-9c4e-410e-add7-e2ba71c94f44.png)

18:25:32,255][_remote.py   : 30] [CODEBUILD] [2022-07-26 16:25:19,924][k8s.py       : 78] ingress[] is empty
[2022-07-26 18:25:32,255][_remote.py   : 30] [CODEBUILD] [2022-07-26 16:25:19,924][k8s.py       : 84] Cannot find Ingress istio-ingress.istio-system
[2022-07-26 18:25:32,256][_remote.py   : 30] [CODEBUILD] [2022-07-26 16:25:19,925][k8s.py       : 88] Waiting for for Ingress istio-ingress.istio-system, sleeping for 1 minute (attempt: 4)

**Expected behavior**

**Screenshots**
Below screenshot shows running pods for istio-system namespace. 
pod "istio-cleanup-secrets-1.1.6-j8qx5" and pod "istio-security-post-install-1.1.6-889gj" are showing "0/1     Completed "
![image](https://user-images.githubusercontent.com/15804600/181068014-5b5589fd-e666-47c7-a109-bdf538eb73f5.png)

Below screenshot shows running pods fo rorbit-system namespace. 
![image](https://user-images.githubusercontent.com/15804600/181068409-ceea42a0-6e84-45e2-93e5-46ca553707be.png)

Below screenshot shows running pods for kube-system namespace. 
![image](https://user-images.githubusercontent.com/15804600/181068587-409d13b7-f688-45a2-8ec2-dacbfdeabe9b.png)

Below screenshot shows running pods for orbit-system-ssm-daemons namespace. 
![image](https://user-images.githubusercontent.com/15804600/181068760-05f392ec-6d02-44a2-ba2e-22ed94bda899.png)

Below screenshot shows running pods for kubeflow namespace. 
![image](https://user-images.githubusercontent.com/15804600/181068970-ee219ea9-cf37-4a39-8785-d54653be9294.png)

Namespaces: knative-serving, anonymous, cert-manager
![image](https://user-images.githubusercontent.com/15804600/181069369-d99d8843-8e3c-4561-8363-0f1488e57e41.png)

ENDPOINTS
![image](https://user-images.githubusercontent.com/15804600/181072298-3c5066ef-5928-4826-b4be-d6b8f7da8058.png)

![image](https://user-images.githubusercontent.com/15804600/181072349-d5b0d72c-47bc-43ae-b29f-f499a57c083b.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by chamcca** [comment]
istio deploys the **alb-ingress-controller** in the **kube-system** namespace. it's worth checking the logs for that pod to see if it is erroring. the ingress controller is responsible for creating the Application Load Balancer (ALB) used as the entrypoint to kubeflow. at times on a failed deployment it will create ALBs but not clean them up and they need to be removed manually so that the ingress controller can recreate them. logs from the ingress controller should have additional info

**Comment by bozethe** [comment]
The logs shows that it fails to create ELB because the VPC doesn't have internet gateway attached to it. See below error.
![image](https://user-images.githubusercontent.com/15804600/181309101-3198d746-410b-4df2-b3a3-92d24f19d406.png)

Our networking setup for our publicly accessible subnets goes through VGW. These are the subnets configured to be used for ELB in the manifest file. 
![image](https://user-images.githubusercontent.com/15804600/181309639-538507a2-39c1-4de3-a020-2374f07cc0fe.png)

Please note: alb-ingress-controller is not in the kube-system but kubeflow namespace. I hope that is fine. 

I created Another nodegroup that is using our public subnets(the one with VGW attached to them) and labeled the alb-ingress-controller to run in that nodegroup. see below.
![image](https://user-images.githubusercontent.com/15804600/181311546-7d7fde93-7b78-4e66-bbde-078c55a1022b.png)
![image](https://user-images.githubusercontent.com/15804600/181311688-7526fbcf-ca3b-41fa-817c-8aa0606f72ab.png)


We have other EKS clusters in other accounts with similar setup and we can access them via ELB attached to the ingress controller.

**Comment by bozethe** [comment]
Managed to find why this is happening. The tag in my subnets were wrong
https://aws.amazon.com/premiumsupport/knowledge-center/eks-load-balancer-controller-subnets/

Resolve the single subnet discovery error
1.    Add the appropriate tags on your subnets to allow the AWS Load Balancer Ingress Controller to create a load balancer using auto-discovery.

Example of private subnets tags:

kubernetes.io/role/internal-elb                Set to 1 or empty tag value for internal load balancers
Example of public subnets tags:

kubernetes.io/role/elb                         Set to 1 or empty tag value for internet-facing load balancers

**Comment by chamcca** [comment]
glad you found that. i was just now getting time to look into it.
