### ISSUE TITLE
[BUG] - add R-studio via custom image

### ISSUE THREAD

**Issue by bozethe** [awslabs/aws-orbit-workbench#1351]
**Describe the bug**
I am trying to extend the features of orbit to include r-studio by using custom image. However the pod fails with "error" status
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/15804600/201042224-1a5da475-e452-4974-812f-e3ce24e1f923.png">

**To Reproduce**
1. login to orbit workbench
2. click New server
3. tick custom image and provide r-studio image pushed into your private ecr
4. Launch

**Expected behavior**
Expecting to be able to use r-studio via custom image

**Screenshots**
❯ kubectl logs studio-0 -n sample-admin-orbit
sh: 1: /usr/local/bin/start.sh: not found

**Additional context**

**Comment by bozethe** [comment]
@chamcca how can we have r-studio to benefit from all the great features of orbit(teams collaboration, secure environment etc)?

are the any plans to incorporate r-studio into orbit?

I have another question that is not connected to the first one. Is it possible to use microsoft AD for authentication instead of cognito? we don't want to go through cognito at all. The requirement is that, orbit should not use cognito at all for auth instead use Microsoft AD.

**Comment by chamcca** [comment]
deploying rstudio into the namespace of a team or team member will automatically enable some of the security protections. the Pod will get the IAM Role and Security Group assigned to the team, which enables collaboration and restriction by team.

to integrate with Microsoft AD, see the documentation on Okta (https://awslabs.github.io/aws-orbit-workbench/okta-integration) and Keycloak (https://awslabs.github.io/aws-orbit-workbench/keycloak-integration) integrations. it should be possible to use the SAML method to integrate Microsoft AD's IdP with Cognito.
