### ISSUE TITLE
[Feature] User should be able to reattach and delete their ebs

### ISSUE THREAD

**Issue by yinweisu** [awslabs/aws-orbit-workbench#206]
1. Currently, the ebs is attached to a server based on its name. If a user is able to choose which ebs he/she wants to attach, it would be more useful.
2. User should be able to delete their ebs when they don't need it anymore. Or some garbage collecting logic for ebs is needed. Otherwise, one can keep starting server with different names and end up with bunch of ebs.

**Comment by abaror** [comment]
It is now supported and EBS notebook was created to demonstrate the use,
