### ISSUE TITLE
Orbit destroy won't remove pypi upstream

### ISSUE THREAD

**Issue by yinweisu** [awslabs/aws-orbit-workbench#265]
Currently destroying the orbit env and foundation won't remove the pypi upstream, which could be annoying and confuses the user.
Solution: recover the ~/.config/pip/pip.conf while destroying the foundation

**Comment by abaror** [comment]
this is a developer job to do , you can just delete ~/.config/pip/pip.conf if you have switch it to code artifact.  The regular installation does not require you to change from pypy
