### ISSUE TITLE
Create run demo page on wiki

### ISSUE THREAD

**Issue by abaror** [awslabs/aws-orbit-workbench#315]
Have a page that starts from deployment of the sample/manifest with lake-creator and lake-user ,  to download demo data, run lake-creator notebook and then run user regression.  Document step by step.

**Comment by abaror** [comment]
Better yet, create a notebook that execute the demo scripts once the deployment is over.

**Comment by stthoom** [comment]
WIP. Using orbit cli run notebook command, creating demo notebook in lake creator teamspace.

**Comment by stthoom** [comment]
Completed demo notebook creation. Merged to main.
