### ISSUE TITLE
The VPC endpoint service com.amazonaws.us-east-1.lambda does not support the availability zone of the subnet: subnet-XXX

### ISSUE THREAD

**Issue by cfregly** [awslabs/aws-orbit-workbench#320]
`orbit deploy foundation -n dev --no-internet-accessibility` is causing this error from the cloudformation logs:

```
The VPC endpoint service com.amazonaws.us-east-1.lambda does not support the availability zone of the subnet: subnet-XXX. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameter; Request ID: XXX; Proxy: null)
```

**Comment by stthoom** [comment]
We are waiting for support from AWS.  For testing, can you please use us-west-2.

**Comment by abaror** [comment]
not much we can do about it until AWS add the support.  If you allow internet access then you don't need it.  otherwise you need to use a region that supports it. 

Closing this as there is no change we need to make

**Comment by abaror** [comment]
we can code in some of the support AZ for now to make few common regions work
