### ISSUE TITLE
CDK Upgrades

### ISSUE THREAD

**Issue by weklund** [awslabs/aws-orbit-workbench#329]
Want to bring light to a larger question on how version bumps should be orchestrated with https://github.com/aws/aws-cdk

Currently, the Orbit CLI uses `1.67`, and the CDK is moving quickly, with its latest release hitting `1.95` last week.

It's not obvious whether to version bump for the latest L2 CDK constructs, even though they are very helpful for future development.  The CDK team makes it clear these minor versions will contain breaking changes.

I'm very new to CDK, so I'm still learning best practices, but would it be helpful to have test coverage on validating various CDK constructs?  Upon research, I see plenty of resources around testing with CDK using Typescript, but not a lot with Python. 🤔 

Genisis for this was from unsupported UserPoolClient construct in cdk 1.67 https://github.com/awslabs/aws-orbit-workbench/pull/295#discussion_r604460247

**Comment by abaror** [comment]
we lock our requirements file to specific versions, and once in awhile when needed we upgrade.  If there is something you need , we can consider updating our cdk version and see it doesn't break anything else.  @chamcca pls review request

**Comment by weklund** [comment]
Ah ok good to know, it wasn't something I _absolutely_ needed, but I think is a nice to have for the change.  I gave specifics in that comment in my PR
