### ISSUE TITLE
Tensorboard connection timeout

### ISSUE THREAD

**Issue by yinweisu** [awslabs/aws-orbit-workbench#410]
Tensorboard is not able to connect. We assume there is some port we need to open in order to make tensorboard to work.

<img width="1069" alt="Screen Shot 2021-04-19 at 10 49 55 AM" src="https://user-images.githubusercontent.com/21029745/115591148-a7d4f180-a286-11eb-881d-f4eaa7f3c58a.png">

**Comment by abaror** [comment]
how did you install Tensorboard?

**Comment by yinweisu** [comment]
We just installed it within orbit. @sxjscience Is that correct?

**Comment by abaror** [comment]
just want to know how, was that helm,  some other way, if you can give me the steps you used.   This link here discuss maybe a way to use it: https://www.tensorflow.org/tensorboard/get_started

**Comment by yinweisu** [comment]
So I think tensorboard comes with tensorflow, and the gpu docker image I deployed has tensorflow. We were trying exactly that tutorial and ended up getting timeout error.

**Comment by sxjscience** [comment]
@abaror we installed tensorboard in the docker and try to use that in notebook via the `%load_ext tensorboard`.
