### ISSUE TITLE
EFA multi-NIC support

### ISSUE THREAD

**Issue by leezu** [awslabs/aws-orbit-workbench#476]
It would be helpful to support EFA with GPUDirectRDMA and multiple NICs (see https://github.com/aws-samples/aws-efa-eks) to support distributed training jobs on p3dn.24xlarge, p4d.24xlarge or g4dn.metal.

**Comment by abaror** [comment]
we will look into this post integration with Kubeflow

**Comment by abaror** [comment]
https://www.openfabrics.org/wp-content/uploads/2019-workshop-presentations/205_RRaja.pdf
