### ISSUE TITLE
Move profiles into custom resource definitions

### ISSUE THREAD

**Issue by abaror** [awslabs/aws-orbit-workbench#517]

**Comment by abaror** [comment]
we can convert the profiles into PodSetting objects.   We will still ask our users to call the orbit build profile to add the profile and in there we will add the pod selector \ container selector. Then we can deploy the podsetting into the team space.  We can have the watcher of podsettings to automatically generate poddefaults for each 'user profile' so they appear in the kubeflow UI

**Comment by abaror** [comment]
the overprovisioning plugin needs to be changed to use a profile instead of hard resource requirements.

**Comment by dgraeber** [comment]
This has been replaced with issues:
https://github.com/awslabs/aws-orbit-workbench/issues/778
https://github.com/awslabs/aws-orbit-workbench/issues/778
https://github.com/awslabs/aws-orbit-workbench/issues/778
https://github.com/awslabs/aws-orbit-workbench/issues/778
