### ISSUE TITLE
Refresh AWS creds on VSCode 

### ISSUE THREAD

**Issue by dgraeber** [awslabs/aws-orbit-workbench#561]
Figure out a way to extend the sts token that the ecs profile generates

**Comment by dgraeber** [comment]
we should leverage this to set the sts timeout to the max:
aws iam update-role --role-name orbit-<env-name>-lake-user-role  --max-session-duration 43200

**Comment by dgraeber** [comment]
Add to IAM CDK on creation of user:
cli/aws_orbit/remote_files/cdk/team_builders/iam.py
cli/aws_orbit/remote_files/cdk/team.py

REF:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Duration.html
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.Role.html

**Comment by abaror** [comment]
@dgraeber pls update status on latest code

**Comment by dgraeber** [comment]
The orbit fix to extend the sts timeout to 12 hours (the max) is in Release 1.0.0.  At last conversation, @abaror  has stated that this is sufficient and that to put a script into a cron job to refresh the token was not needed.

The SDE team at AWS working on AWS Toolkit is in process to support ecs-container roles on the extension so that credentials are not needed.  REF: https://sim.amazon.com/issues/IDE-1857
