### ISSUE TITLE
Install the SageMaker logs kubectl plugin

### ISSUE THREAD

**Issue by abaror** [awslabs/aws-orbit-workbench#577]
on this page https://docs.aws.amazon.com/sagemaker/latest/dg/amazon-sagemaker-operators-for-kubernetes.htm 
they explain how to install the kubectl plugin to get into the sm jobs logs

we should install this on our user image so users can access the logs

**Comment by dgraeber** [comment]
I have this vetted and working..it is a very simple download.  But, it is unclear how I can add to the PATH when firing up the image.

**Comment by dgraeber** [comment]
SMLogs libraries are successfully installed on jupyter-user image and are executed via kubectl smlogs <crd> <job-name>. When updating the regression testing, the library has issues with reading the ./kube/config auth setup.

**Comment by dgraeber** [comment]
The ./kube/config that we are currently using is not sufficient to make this call.  Quick testing indicates that the certificate, server and other pertinent info is required.  A change to the create_kubeconfig.py in the jupyter-user image is necessary.
