### ISSUE TITLE
Need to initialize the .bashrc on home folder for conda

### ISSUE THREAD

**Issue by abaror** [awslabs/aws-orbit-workbench#606]
```
(/data/conda/myenv) jovyan@a1-0:~$ cat .bashrc 

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/conda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/conda/etc/profile.d/conda.sh" ]; then
        . "/opt/conda/etc/profile.d/conda.sh"
    else
        export PATH="/opt/conda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

**Comment by abaror** [comment]
we should add this to the pod that initialize the home directory for a user in the user space helm.

**Comment by chamcca** [comment]
bashrc is included in the image as /opt/orbit/bashrc

**Comment by abaror** [comment]
the starting jupyter script calls this : run-hooks /usr/local/bin/before-notebook.d 

so we can put into this folder a starting script that checks if ~/.bashrc exists and if not , then copy from /opt/orbit/bashrc

**Comment by abaror** [comment]
incorporate this for the conda support.  Add this to the docker image

**Comment by stthoom** [comment]
After adding below in /aws-orbit-workbench/cli/aws_orbit/data/charts/user/user-space/templates/copy_vscode_ext.yaml file, able to see the .bashrc file in home directory. 

cp /opt/orbit/bashrc /home/jovyan/.bashrc;

**Comment by stthoom** [comment]
https://github.com/awslabs/aws-orbit-workbench/pull/700/files

Waiting for merge.
