### ISSUE TITLE
An error occurred (DeleteConflict) when calling the DeleteRole  operation: Cannot delete entity, must delete policies first.

### ISSUE THREAD

**Issue by rb201** [awslabs/aws-orbit-workbench#633]
The kf roles need to have their attached policies removed first. Initially on destroy, we delete all policies, but we agreed that if we wouldnt want to remove eg an AWS managed policy.  

The code was then changed to check if the policy starts with "kf-", and to remove those. But the current policies we attach have not had their names changed to reflect that check. So the error is produced because the kf- roles have policy names like iam_blahblah

**Comment by abaror** [comment]
believe this was fixed, @rb201 ?
