### ISSUE TITLE
Build Image Bug

### ISSUE THREAD

**Issue by yinweisu** [awslabs/aws-orbit-workbench#645]
[sh.py : 30] Step 23/48 : ADD pip.conf /etc/pip.conf
[sh.py : 30] ADD failed: stat /var/lib/docker/tmp/docker-builder468196469/pip.conf: no such file or directory

As talked with @chamcca, this is caused by some regression issue. Create this issue for better tracking

**Comment by srinivasreddych** [comment]
Discussed with @chamcca. This is fixed
