### ISSUE TITLE
Docker build out of space

### ISSUE THREAD

**Issue by yinweisu** [awslabs/aws-orbit-workbench#649]
Code Build will run into out of space issue if the image already exists because it will try to pull the image and build on cache.

**Comment by abaror** [comment]
We need to fix codebuild to use a different folder for docker daemon.

**Comment by srinivasreddych** [comment]
@yinweisu Can you provide me detailed steps on how to replicate the issue?

**Comment by yinweisu** [comment]
After the env got deployed, orbit build a GPU image once. Then, make some change to the image and rebuild it. The image might have to be large enough to replicate the issue.
