### ISSUE TITLE
Unable to delete trainingjob.sagemaker.aws.amazon.com

### ISSUE THREAD

**Issue by rb201** [awslabs/aws-orbit-workbench#665]
aws_orbit/remote_files/destroy.py:70 hangs when encounters the trainingjob.sagemaker.aws.amazon.com resource "xgboost-mnist-sm-operator-xxxx". Force delete doesnt do anything. It just hangs, and therefore destroy teams codebuild times out.

I manually ran this command to get moving 
kubectl patch trainingjob xgboost-mnist-sm-operator-959r -n lake-user -p '{"metadata": {"finalizers":[]}}' --type=merge

**Comment by abaror** [comment]
I changed the order of the destroy to first destroy the trainingjobs and then destroy deployment which will destroy the operator. That seems to fix it.
