### ISSUE TITLE
Ray Jobs are not working.

### ISSUE THREAD

**Issue by abaror** [awslabs/aws-orbit-workbench#677]
Example-3-Ray-Job-Example.ipynb. 

Created Ray job creates pod but the logs show "1.0 nodes have joined so fat, waiting for 1.,0 more." 

Need to check the root cause and fix the health of Ray cluster.

**Comment by stthoom** [comment]
Given ray plugin details in lake-user team plugin manifest file. 
-   PluginId: ray
    Module: ray
    Parameters:
        workers: 3
        release_tag: 1.3.0

From lake-user namespace, can see 1 head and 3 worker nodes. Still worker nodes are not joining. 

Finding from ray head pod. 
--
(base) ray@ray-head-74d6c85dcc-r6jq6:~$ 
(base) ray@ray-head-74d6c85dcc-r6jq6:~$ ray status
======== Cluster status: 2021-07-19 05:29:49.622600 ========
Node status
------------------------------------------------------------
 1 node(s) with resources: {'memory': 19885820315.0, 'CPU': 1.0, 'object_store_memory': 9942910156.0, 'node:10.0.16.157': 1.0}

Resources
------------------------------------------------------------
Usage:
 0.0/1.0 CPU
 0.00/18.520 GiB memory
 0.00/9.260 GiB object_store_memory

**Comment by stthoom** [comment]
By submitting ray job with 1 node, successfully completed job. Need to identify the root cause of Ray head not able to acquire worked nodes.

**Comment by stthoom** [comment]
https://github.com/awslabs/aws-orbit-workbench/pull/852

Adding below to ray head pod allowed communication from worker pods.

headLabels:
  orbit/attach-security-group: "yes"

Testing - 
1) Verified Orbit ray job notebook execution with 2 workers. 
2) Ray tuning job status in running even after 15 hours. Need to see the reason for pending status.
