### ISSUE TITLE
Sample notebooks automatically perform S3 bucket sync when scheduling notebook run, overwriting local notebook changes

### ISSUE THREAD

**Issue by antje** [awslabs/aws-orbit-workbench#690]
Identified behaviour in Orbit v0.15.0. 

When scheduling a notebook execution via 
%%run_notebook or %%schedule_notebook, the bootstrap process runs copy_samples.sh which syncs the sample notebooks with the S3 Orbit bucket, overwriting any local notebook changes. 

Workaround: 

After initial Orbit installation, 

1/ Delete copy_samples.sh for the affected teams in the following S3 path and locally:
aws s3 rm s3://${AWS_ORBIT_S3_BUCKET}/teams/${AWS_ORBIT_TEAM_SPACE}/bootstrap/copy_samples.sh
rm ~/.orbit/bootstrap/scripts/copy_samples.sh

2/ Checkout the sample notebooks (for relevant Orbit version) again and put in ~/shared/samples/ folder: 
git checkout tags/<ORBIT_VERSION_TAG>
cp -R notebooks/ ~/shared/samples/

3/ Comment out the aws s3 sync command in each team's local installation: 
/home/jovyan/shared/samples/copy_samples.sh

**Comment by dgraeber** [comment]
We have removed this functionality and now the notebooks reside in a docker image.  Your notebooks should not be overwritten unless the copy-samples-data job is run via the script-runner plugin.

Please contact me to elaborate?
