### ISSUE TITLE
H-Model-Development sample notebooks fail due to 2G memory constraints in Orbit Demo environment

### ISSUE THREAD

**Issue by antje** [awslabs/aws-orbit-workbench#691]
Identified behaviour in Orbit v0.15.0

When installing Orbit via the Quick Demo Deployment Guide (https://awslabs.github.io/aws-orbit-workbench/quick-demo-deployment), the manifest only contains a 2GB image which doesn't provide enough resources to succesfully execute the ML sample notebooks (https://github.com/awslabs/aws-orbit-workbench/tree/main/samples/notebooks/H-Model-Development). 

Workaround: 

1/ Create a new profile.json file:

```
[{
        "display_name": "notebook8G2C",
        "description": "Notebook with 8GB",
        "kubespawner_override": {
            "cpu_guarantee": 2,
            "cpu_limit": 2,
            "mem_guarantee": "4G",
            "mem_limit": "8G"
        }
}]
```

2/ Run the following command, change $AWS_ORBIT_ENV and $AWS_ORBIT_TEAM_SPACE to your environment.

orbit build profile --debug --env $AWS_ORBIT_ENV --team $AWS_ORBIT_TEAM_SPACE profile.json

3/ Select the new image to run the ML notebooks.

**Comment by dgraeber** [comment]
The use of profiles has been replaced with 'podsettings' and is demonstrated in our sample notebooks (see the I-images folder or M-Admin folders).  You can create a podsetting with the resources desired, and a poddefault will automatically be created and available in the Notebooks Servers configuration dropdown.

Contact me if you have questions?
