### ISSUE TITLE
Test stability of demo environment

### ISSUE THREAD

**Issue by NickCorbett** [awslabs/aws-orbit-workbench#776]
The demo environment works, but is not stable - will break if left running for some time

**Comment by NickCorbett** [comment]
Goal of this task is to identify issues and create issues, not to solve within this ticket

**Comment by srinivasreddych** [comment]
#771

**Comment by srinivasreddych** [comment]
#791

**Comment by srinivasreddych** [comment]
#795 - Cleanup of teams

**Comment by srinivasreddych** [comment]
#797 - Cleanup of teams

**Comment by srinivasreddych** [comment]
#799 - Deployment of teams

**Comment by rb201** [comment]
#810 - deploying lustre
