### ISSUE TITLE
`helm uninstall all` missing arg

### ISSUE THREAD

**Issue by srinivasreddych** [awslabs/aws-orbit-workbench#797]
During the teams destroy phase, following error popped up:

[2021-07-15 22:16:37,010][remote.py    : 31] [CODEBUILD]
[helm.py      :165] Uninstalling all charts in namespace lake-admin
[sh.py        : 28] + ./uninstall_namespace_charts.sh lake-admin
 [sh.py        : 30] + NAMESPACE=lake-admin
+ helm ls --all --short -n lake-admin
[sh.py        : 30] + xargs -L1 helm uninstall --debug -n lake-admin
[sh.py        : 30] Error: "helm uninstall" requires at least 1 argument

**Comment by stthoom** [comment]
https://github.com/Praqma/helmsman/issues/502 

Seems the namespace being passed as empty and "-n" is eating the passed chart name value. 


def uninstall_all_charts(namespace: str) -> None:
    try:
        _logger.debug("Uninstalling all charts in namespace %s", namespace)
        sh.run(f"./uninstall_namespace_charts.sh {namespace}", cwd=CHARTS_PATH)
    except exceptions.FailedShellCommand as e:
        _logger.error(e)


set -ex
NAMESPACE=${1}

helm ls --all --short -n ${NAMESPACE} | xargs -L1 helm uninstall --debug -n ${NAMESPACE}
