### ISSUE TITLE
Exception: FSX Volume is not ready for plugin fast-fs-lustre

### ISSUE THREAD

**Issue by rb201** [awslabs/aws-orbit-workbench#810]
Events from pod/chmod-fsx-job-lake-user-wqh2c in lake-user namespace:
`Events:
  Type     Reason             Age                     From                Message
  ----     ------             ----                    ----                -------
  Normal   NotTriggerScaleUp  9m43s (x1626 over 14h)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 2 running "VolumeBinding" filter plugin for pod "chmod-fsx-job-lake-user-wqh2c": pod has unbound immediate PersistentVolumeClaims, 1 node(s) didn't match node selector
  Warning  FailedScheduling   4m52s (x820 over 14h)   default-scheduler   0/5 nodes are available: 5 pod has unbound immediate PersistentVolumeClaims.
  Normal   NotTriggerScaleUp  4m41s (x3643 over 14h)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) didn't match node selector, 2 running "VolumeBinding" filter plugin for pod "chmod-fsx-job-lake-user-wqh2c": pod has unbound immediate PersistentVolumeClaims
`

Event from pvc luster-lake-user-fs-fast-fs-lustre:
`persistentvolume-controller  waiting for a volume to be created, either by external provisioner "fsx.csi.aws.com" or manually created by system administrator
`

**Comment by stthoom** [comment]
Created new EKS cluster and deployed https://github.com/kubernetes-sigs/aws-fsx-csi-driver/tree/master/examples/kubernetes/dynamic_provisioning_s3 to test the PV creation. 

Could replicate similar issue of no PV creation when creating POD with FSX luster based storage class.

**Comment by chamcca** [comment]
closing duplicate
