### ISSUE TITLE
Safe input loading in YAML parser

### ISSUE THREAD

**Issue by NickCorbett** [awslabs/aws-orbit-workbench#859]
Handle untrusted data in PyYaml library
It is not safe to call yaml.load or yaml.load_all with any data received from an untrusted source! yaml.load is as powerful as pickle.load and so may call any Python function.

Instead, you should use yaml.safe_load(stream) or yaml.safe_load_all(stream) function to handle untrusted data. Please refer to PyYaml documentation to learn about how to use these two functions.

Code reference:

https://github.com/awslabs/aws-orbit-workbench/blob/bee15c1ca78a78afe35b3b53ca54278c90d60514/plugins/custom_cfn/custom_cfn/cdk.py#L170-L170

**Comment by stthoom** [comment]
https://github.com/awslabs/aws-orbit-workbench/pull/874

**Comment by stthoom** [comment]
Changing the custom loader class to CfnSafeYamlLoader(yaml.SafeLoader)
