### ISSUE TITLE
Can't launch up servers

### ISSUE THREAD

**Issue by yinweisu** [awslabs/aws-orbit-workbench#898]
As stated in the title. Tried delete the notebook and create a new one but ended up with same issue.
![image (2)](https://user-images.githubusercontent.com/21029745/129072606-fcaac38f-21b5-4173-9d34-f3461344e6d5.png)

**Comment by dgraeber** [comment]
It was determined that this was due to namespace collision within Kubeflow (opposed to Orbit namespace generation).  Clearing out the namespace and dependent artifacts, letting orbit regenerate them alleviated this situation.
